title: PAT Solution in C
author: LuXu
email: oliver_lew@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  浙江大学编程能力测试(PAT)C语言题解说明
baseurl: "/PAT" # the subpath of your site, e.g. /blog
url: "http://oliverlew.github.io/PAT/" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  oliverlew
rss: rss

plugins:
  - jekyll-feed

# Build settings
github: [metadata]
encoding: UTF-8
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
future: true
show_excerpts: false

theme: minima

header_pages:
  - categories/Basic.md
  - categories/Advanced.md
  - categories/Top.md
  - about.md

exclude: 
  - PATAdvanced/
  - PATBasic/
  - Gemfile
  - Gemfile.lock
  - source
  - README.md
  - _articles/html
  - _articles/analysis

# collections
collections:
  articles:
    output: true

# Google Analytics
google_analytics: UA-118900116-1

# vim:tabstop=2:softtabstop=2:shiftwidth=2
